#!/bin/bash

hc() {
    herbstclient "$@"
}

# Apps
TERMINAL=alacritty
BROWSER=microsoft-edge-stable
MUSIC=spotify
SCREENSHOTER=xfce4-screenshooter

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
# Mod=Mod1    # Use alt as the main modifier
Mod=Mod4 # Use the super key as the main modifier

hc keybind $Mod-Shift-q quit                                  # Quit session
hc keybind $Mod-Shift-r reload                                # Reload HLWM
hc keybind $Mod-Shift-p spawn ~/.config/polybar/launch        # Reload Polybar
hc keybind $Mod-q spawn ~/.config/polybar/scripts/launcher.sh # Launch AppLauncher
hc keybind $Mod-w close                                       # Close Focused App
hc keybind $Mod-e spawn nautilus

hc keybind $Mod-grave spawn "${TERMINAL:-xterm}" # use your $TERMINAL with xterm as fallback
hc keybind $Mod-period spawn emote
hc keybind $Mod-slash spawn code

hc keybind $Mod-F3 spawn $MUSIC
hc keybind $Mod-F5 spawn $BROWSER
hc keybind $Mod-F6 spawn $SCREENSHOTER

# Layout Swap
hc keybind $Mod-F9 spawn herbstclient set_layout grid
hc keybind $Mod-F10 spawn herbstclient set_layout max
hc keybind $Mod-F11 spawn herbstclient set_layout horizontal
hc keybind $Mod-F12 spawn herbstclient set_layout vertical

hc keybind $Mod-n spawn ~/.config/herbstluftwm/scripts/numlock --toggle

# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-Left focus left
hc keybind $Mod-Down focus down
hc keybind $Mod-Up focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left shift left
hc keybind $Mod-Shift-Down shift down
hc keybind $Mod-Shift-Up shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u split bottom 0.5
hc keybind $Mod-o split right 0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h resize left +$resizestep
hc keybind $Mod-Control-j resize down +$resizestep
hc keybind $Mod-Control-k resize up +$resizestep
hc keybind $Mod-Control-l resize right +$resizestep
hc keybind $Mod-Control-Left resize left +$resizestep
hc keybind $Mod-Control-Down resize down +$resizestep
hc keybind $Mod-Control-Up resize up +$resizestep
hc keybind $Mod-Control-Right resize right +$resizestep

# tags
tag_names=({1..4})
tag_keys=({1..4} 0)

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}"; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ]; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-Shift-period use_index +1 --skip-visible
hc keybind $Mod-Shift-comma use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-s set_attr clients.focus.floating toggle
hc keybind $Mod-x set_attr clients.focus.minimized true
hc keybind $Mod-Shift-x jumpto last-minimized
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space \
    or , and . compare tags.focus.curframe_wcount = 2 \
    . cycle_layout +1 vertical horizontal max vertical grid \
    , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace cycle_monitor
hc keybind $Mod-Tab cycle_all +1
hc keybind $Mod-Shift-Tab cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# Media
hc keybind XF86AudioPlay spawn ~/.config/herbstluftwm/scripts/media play-pause
hc keybind XF86AudioPause spawn ~/.config/herbstluftwm/scripts/media pause
hc keybind XF86AudioPrev spawn ~/.config/herbstluftwm/scripts/media previous
hc keybind XF86AudioNext spawn ~/.config/herbstluftwm/scripts/media next

# Sound/Volume
hc keybind XF86AudioRaiseVolume spawn amixer -D pulse sset Master 2%+ # Volume++
hc keybind XF86AudioLowerVolume spawn amixer -D pulse sset Master 2%- # Volume--
hc keybind XF86AudioMute spawn amixer -D pulse sset Master toggle

# Display Brightness
hc keybind XF86MonBrightnessOnOff spawn brightnessctl set +5%
hc keybind XF86MonBrightnessUp spawn brightnessctl set +5%
hc keybind XF86MonBrightnessDown spawn brightnessctl set 5%-

# Keyboard Backlight
hc keybind XF86KbdBrightnessUp spawn brightnessctl -d asus::kbd_backlight set 1+
hc keybind XF86KbdBrightnessDown spawn brightnessctl -d asus::kbd_backlight set 1-

hc keybind Num_Lock spawn ~/.config/herbstluftwm/scripts/numlock